version: '2'
services:
    iterationservice-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        command: mongos --configdb iterationservice-mongodb-config
    iterationservice-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    iterationservice-mongodb-config:
        image: mongo:3.4.8
        container_name: iterationservice-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
